# .github/workflows/publish.yml
name: Publish

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: flutter/flutter
          fetch-depth: 0
          ref: stable
          path: build

      - run: sudo apt install -y curl git unzip xz-utils zip libglu1-mesa

      - run: build/bin/flutter pub get
      
      - run: ../build/bin/flutter build web --base-href /flutter_video_view/ --wasm --release -t lib/main_advanced.dart
        working-directory: ./example

      - run: perl -pi -e 's/"flutter_bootstrap.js":[^\n]+//g' flutter_service_worker.js

      - run: perl -pi -e 's/"flutter_bootstrap.js"/"flutter.js"/g' flutter_service_worker.js

      - run: perl -pi -e "s/location\.origin/location.href.replace(\/\\\\\/[^\/]+\\$\/, '')/g" example/build/web/flutter_service_worker.js

      - run: perl -0777 -pi -e "s/\n *if \(key == \"\"\) {[^}]+}| \|\| key == ''//g" example/build/web/flutter_service_worker.js

      - run: rm -f example/build/web/flutter_bootstrap.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'example/build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - run: mkdir -p ~/.config/dart
      
      - shell: bash
        env:
          CREDENTIAL_JSON: ${{ secrets.CREDENTIAL_JSON }}
        run: echo "$CREDENTIAL_JSON" > ~/.config/dart/pub-credentials.json

      - run: build/bin/flutter pub publish -f
